version: '3.8'
services:
 db:
  image: postgres
  restart: always
  ports:
   - '5432:5432'
  volumes:
   - ./postgres_data:/var/lib/postgesql/data
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASS}
